name: Main

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set container details
        run: |
          echo "::set-env name=REGISTRY::docker.pkg.github.com"
          REPOSITORY_BASE=$(echo "${{ github.repository }}" | perl -ne 'print lc')
          echo "::set-env name=REPOSITORY_BASE::${REPOSITORY_BASE}"
          echo "::set-env name=TAG::sha-$(git rev-parse --short=7 HEAD)"
      - name: Build containers
        run: |
          docker build -t "${REGISTRY}/${REPOSITORY_BASE}/app:${TAG}" .
      - name: Push containers (except on PRs from forks)
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login "${REGISTRY}" -u ${{ github.actor }} --password-stdin
          docker push "${REGISTRY}/${REPOSITORY_BASE}/app:${TAG}"
      - name: Push latest containers (only on main)
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/master' }}
        run: |
          docker tag "${REGISTRY}/${REPOSITORY_BASE}/app:${TAG}" "${REGISTRY}/${REPOSITORY_BASE}/app:latest"
          docker push "${REGISTRY}/${REPOSITORY_BASE}/app:latest"
